import { CustomThemeConfig, PresetThemeId } from '../types';

export interface ThemePresetDefinition {
  id: PresetThemeId;
  name: string;
  tagline: string;
  category: 'Dark Fire' | 'Cyberpunk' | 'Cosmic' | 'Botanical' | 'Café' | 'Minimalist' | 'Vibrant';
  previewColors: string[]; // 3 colors for visual swatch preview
  config: CustomThemeConfig;
}

export const THEME_PRESETS: ThemePresetDefinition[] = [
  {
    id: 'monochrome-minimalist',
    name: 'Dark Minimalist',
    tagline: 'Distraction-free pure black & white monochrome aesthetic',
    category: 'Minimalist',
    previewColors: ['#000000', '#ffffff', '#71717a'],
    config: {
      presetId: 'monochrome-minimalist',
      mode: 'dark',
      primaryColor: '#ffffff',
      secondaryColor: '#a1a1aa',
      customBackgroundColor: '#09090b',
      borderRadius: 'md',
      cardGlow: 'none',
      glassmorphism: false,
      cardStyle: 'solid',
      contentScrimOpacity: 0.95,
      backgroundPattern: 'none',
      wallpaperOpacity: 0,
      wallpaperBlur: 0,
      fireIntensity: 'off',
      fireEmberCount: 0,
      showBaseFlames: false,
    },
  },
  {
    id: 'obsidian-flame',
    name: 'Obsidian Flame',
    tagline: 'Mystic dark purple fire & floating combustion embers',
    category: 'Dark Fire',
    previewColors: ['#07020d', '#9333ea', '#c084fc'],
    config: {
      presetId: 'obsidian-flame',
      mode: 'dark',
      primaryColor: '#9333ea',
      secondaryColor: '#c084fc',
      customBackgroundColor: '#07020d',
      borderRadius: 'md',
      cardGlow: 'subtle',
      glassmorphism: false,
      cardStyle: 'solid',
      contentScrimOpacity: 0.85,
      backgroundPattern: 'fire',
      wallpaperOpacity: 0.35,
      wallpaperBlur: 3,
      fireIntensity: 'normal',
      fireEmberCount: 35,
      showBaseFlames: true,
    },
  },
  {
    id: 'midnight-cyberpunk',
    name: 'Midnight Cyberpunk',
    tagline: 'High-contrast neon cyan & hot magenta synthwave',
    category: 'Cyberpunk',
    previewColors: ['#05070e', '#06b6d4', '#ec4899'],
    config: {
      presetId: 'midnight-cyberpunk',
      mode: 'dark',
      primaryColor: '#06b6d4',
      secondaryColor: '#ec4899',
      customBackgroundColor: '#05070e',
      borderRadius: 'sm',
      cardGlow: 'subtle',
      glassmorphism: false,
      cardStyle: 'solid',
      contentScrimOpacity: 0.85,
      backgroundPattern: 'grid',
      wallpaperOpacity: 0.3,
      wallpaperBlur: 4,
      fireIntensity: 'subtle',
      fireEmberCount: 20,
      showBaseFlames: false,
    },
  },
  {
    id: 'cosmic-nebula',
    name: 'Cosmic Nebula',
    tagline: 'Interstellar deep navy, aura violet & starlight sparks',
    category: 'Cosmic',
    previewColors: ['#0b0c1b', '#6366f1', '#a855f7'],
    config: {
      presetId: 'cosmic-nebula',
      mode: 'dark',
      primaryColor: '#6366f1',
      secondaryColor: '#a855f7',
      customBackgroundColor: '#0b0c1b',
      borderRadius: 'lg',
      cardGlow: 'subtle',
      glassmorphism: false,
      cardStyle: 'solid',
      contentScrimOpacity: 0.85,
      backgroundPattern: 'nebula',
      wallpaperOpacity: 0.35,
      wallpaperBlur: 6,
      fireIntensity: 'subtle',
      fireEmberCount: 30,
      showBaseFlames: false,
    },
  },
  {
    id: 'emerald-forest',
    name: 'Emerald Botanical',
    tagline: 'Calming deep evergreen, organic sage & mint focus',
    category: 'Botanical',
    previewColors: ['#03140c', '#10b981', '#34d399'],
    config: {
      presetId: 'emerald-forest',
      mode: 'dark',
      primaryColor: '#10b981',
      secondaryColor: '#34d399',
      customBackgroundColor: '#03140c',
      borderRadius: 'md',
      cardGlow: 'subtle',
      glassmorphism: false,
      cardStyle: 'solid',
      contentScrimOpacity: 0.85,
      backgroundPattern: 'waves',
      wallpaperOpacity: 0.35,
      wallpaperBlur: 5,
      fireIntensity: 'off',
      fireEmberCount: 15,
      showBaseFlames: false,
    },
  },
  {
    id: 'warm-espresso',
    name: 'Warm Espresso Café',
    tagline: 'Cozy study lounge, roasted caramel & amber candlelight',
    category: 'Café',
    previewColors: ['#120d09', '#d97706', '#fbbf24'],
    config: {
      presetId: 'warm-espresso',
      mode: 'dark',
      primaryColor: '#d97706',
      secondaryColor: '#fbbf24',
      customBackgroundColor: '#120d09',
      borderRadius: 'md',
      cardGlow: 'subtle',
      glassmorphism: false,
      cardStyle: 'solid',
      contentScrimOpacity: 0.85,
      backgroundPattern: 'none',
      wallpaperOpacity: 0.3,
      wallpaperBlur: 4,
      fireIntensity: 'subtle',
      fireEmberCount: 20,
      showBaseFlames: false,
    },
  },
  {
    id: 'sunset-crimson',
    name: 'Sunset Crimson',
    tagline: 'Warm electric rose, dusk wine & passionate glow',
    category: 'Vibrant',
    previewColors: ['#14040a', '#f43f5e', '#fb7185'],
    config: {
      presetId: 'sunset-crimson',
      mode: 'dark',
      primaryColor: '#f43f5e',
      secondaryColor: '#fb7185',
      customBackgroundColor: '#14040a',
      borderRadius: 'md',
      cardGlow: 'subtle',
      glassmorphism: false,
      cardStyle: 'solid',
      contentScrimOpacity: 0.85,
      backgroundPattern: 'fire',
      wallpaperOpacity: 0.35,
      wallpaperBlur: 4,
      fireIntensity: 'normal',
      fireEmberCount: 30,
      showBaseFlames: true,
    },
  },
  {
    id: 'nordic-slate',
    name: 'Nordic Slate',
    tagline: 'Architectural minimalism, cool steel & distraction-free gray',
    category: 'Minimalist',
    previewColors: ['#0f172a', '#64748b', '#94a3b8'],
    config: {
      presetId: 'nordic-slate',
      mode: 'dark',
      primaryColor: '#64748b',
      secondaryColor: '#94a3b8',
      customBackgroundColor: '#0f172a',
      borderRadius: 'sm',
      cardGlow: 'none',
      glassmorphism: false,
      cardStyle: 'solid',
      contentScrimOpacity: 0.90,
      backgroundPattern: 'grid',
      wallpaperOpacity: 0.25,
      wallpaperBlur: 2,
      fireIntensity: 'off',
      fireEmberCount: 0,
      showBaseFlames: false,
    },
  },
  {
    id: 'pure-light',
    name: 'Pure Clean Light',
    tagline: 'Bright academia, crisp off-white canvas & regal violet',
    category: 'Minimalist',
    previewColors: ['#f8fafc', '#7c3aed', '#4f46e5'],
    config: {
      presetId: 'pure-light',
      mode: 'light',
      primaryColor: '#7c3aed',
      secondaryColor: '#4f46e5',
      customBackgroundColor: '#f8fafc',
      borderRadius: 'md',
      cardGlow: 'none',
      glassmorphism: false,
      cardStyle: 'solid',
      contentScrimOpacity: 0.90,
      backgroundPattern: 'none',
      wallpaperOpacity: 0.2,
      wallpaperBlur: 3,
      fireIntensity: 'off',
      fireEmberCount: 0,
      showBaseFlames: false,
    },
  },
];

export const CURATED_WALLPAPERS = [
  {
    id: 'cozy-library',
    name: 'Cozy Vintage Library',
    category: 'Study & Academia',
    thumbnail: 'https://images.unsplash.com/photo-1507842229450-c6468a52f829?auto=format&fit=crop&w=400&q=70',
    fullUrl: 'https://images.unsplash.com/photo-1507842229450-c6468a52f829?auto=format&fit=crop&w=1920&q=80',
  },
  {
    id: 'deep-nebula',
    name: 'Deep Purple Galaxy',
    category: 'Cosmic & Space',
    thumbnail: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=400&q=70',
    fullUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1920&q=80',
  },
  {
    id: 'lofi-desk',
    name: 'Night Lo-Fi Desk',
    category: 'Study & Chill',
    thumbnail: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=400&q=70',
    fullUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1920&q=80',
  },
  {
    id: 'rainy-cafe',
    name: 'Rainy City Lights',
    category: 'Atmospheric',
    thumbnail: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=400&q=70',
    fullUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1920&q=80',
  },
  {
    id: 'dark-minimal',
    name: 'Obsidian Minimal Arch',
    category: 'Clean Dark',
    thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=400&q=70',
    fullUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1920&q=80',
  },
];

export const CURATED_VIDEOS = [
  {
    id: 'fireplace-ember',
    name: 'Cozy Hearth Fireplace',
    category: 'Warm & Calming',
    thumbnail: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=70',
    videoUrl: '/videos/fireplace.mp4',
  },
  {
    id: 'rainy-window',
    name: 'Rain On Night Window',
    category: 'Study & Focus',
    thumbnail: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=400&q=70',
    videoUrl: '/videos/rainfall.mp4',
  },
  {
    id: 'sunset-ocean-tide',
    name: 'Twilight Ocean Shore',
    category: 'Relaxing Nature',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=70',
    videoUrl: '/videos/ocean.mp4',
  },
  {
    id: 'deep-space-stars',
    name: 'Deep Galactic Drift',
    category: 'Cosmic & Space',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=70',
    videoUrl: '/videos/cosmic_nebula.mp4',
  },
  {
    id: 'cyberpunk-tunnel',
    name: 'Cyberpunk Neon Drift',
    category: 'High Energy',
    thumbnail: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=400&q=70',
    videoUrl: '/videos/cyber_grid.mp4',
  },
  {
    id: 'aurora-borealis',
    name: 'Northern Aurora Veil',
    category: 'Peaceful Ambient',
    thumbnail: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=400&q=70',
    videoUrl: '/videos/aurora_drift.mp4',
  },
];

export const CURATED_AUDIO = [
  {
    id: 'synth-rain',
    name: 'Gentle Rain & Distant Thunder',
    type: 'procedural' as const,
    soundType: 'rain' as const,
    tagline: 'Infinite soothing rainfall & warm rolling thunder',
  },
  {
    id: 'synth-fireplace',
    name: 'Crackling Fireplace Embers',
    type: 'procedural' as const,
    soundType: 'fireplace' as const,
    tagline: 'Authentic warm wood pops & soft hearth glow',
  },
  {
    id: 'synth-drone',
    name: 'Deep Cosmic Binaural Tone (432Hz)',
    type: 'procedural' as const,
    soundType: 'cosmic' as const,
    tagline: 'Calming alpha-wave frequencies for deep study concentration',
  },
  {
    id: 'synth-chords',
    name: 'Lo-Fi Ambient Piano Chords',
    type: 'procedural' as const,
    soundType: 'lofi' as const,
    tagline: 'Warm electric keys drifting over an analog tape bed',
  },
];

export const AMBIENT_SOUNDSCAPES = CURATED_AUDIO;

export const DEFAULT_THEME_CONFIG: CustomThemeConfig = {
  ...THEME_PRESETS[0].config,
  contentScrimOpacity: 0.95,
  cardStyle: 'solid',
  videoOpacity: 0,
  videoBlur: 0,
  audioVolume: 0.5,
  zenMode: false,
};
